url: https://emk4.github.io/survival-chronicles.github.io
baseurl: /survival-chronicles.fr/
# Site settings
title: Survival chronicles
email: emkal@survival-chronicles.com
description: "Chronicles of a french IT engineer trying to make his way in Tokyo"


#author
author:
  name: 'Emka'


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Emkasec
  - title: envelope
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: rss
    url: 'feed.xml'

# credit
people:
- name: Emka
  pic: 1

# social

#disqus:
 # name: survival-chronicles
 # public_key: 16I9Q3peU6sDEEzM1v1DtRNOB6awZGnZkqIktUxtrr68Y1kxY4pHmLFxSrWjHCWX

# Build settings
markdown: kramdown
permalink: pretty
exclude: [vendor]


