url: http://survival-chronicles.fr
baseurl: 
# Site settings
title: Survival chronicles
email: bbellecour@gmail.com
description: "Chronicles of a french IT engineer trying to make his way in Tokyo"


#author
author:
  name: 'Emka'


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Emkasec
  - title: envelope
    url: http://survival-chronicles.fr/contact/
  - title: rss
    url: http://survival-chronicles.fr/feed.xml

# credit
people:
- name: Emka
  pic: 1

# social

#disqus:
 # name: survival-chronicles
 # public_key: 16I9Q3peU6sDEEzM1v1DtRNOB6awZGnZkqIktUxtrr68Y1kxY4pHmLFxSrWjHCWX

#gems:
gems:
  - jekyll-sitemap
  - github-pages

# Build settings
markdown: kramdown
permalink: pretty
exclude: [vendor]


