url: http://survival-chronicles.fr
baseurl: 
# Site settings
title: Survival chronicles
email: Your mail
description: "Your site meta description"


#author
author:
  name: 'Your name'


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/yourID
  - title: envelope
    url: https://emk4.github.io/survival-chronicles.github.io/contact/
  - title: rss
    url: https://emk4.github.io/survival-chronicles.github.io/feed.xml

# credit
people:
- name: Credit name
  pic: 1

# social

#disqus:
 # name: survival-chronicles
 # public_key: Your pub key

#gems:
gems:
  - jekyll-sitemap
  - github-pages

# Build settings
markdown: kramdown
permalink: pretty
exclude: [vendor]


